### ISSUE TITLE
Updating to latest EAIntroView version will cause crash

### ISSUE THREAD

**Issue by hkellaway** [RefugeRestrooms/refugerestrooms-ios#102]
https://www.versioneye.com/objective-c/eaintroview/2.7.0

**Comment by hkellaway** [comment]
Crash caused when new version of EAIntroView used:

*** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 5 beyond bounds [0 .. 4]'

**Comment by kadirarlii** [comment]
Thank u.
2.6.4 is working for me.
