### ISSUE TITLE
Wrap user-facing strings in NSLocalizedString

### ISSUE THREAD

**Issue by hkellaway** [RefugeRestrooms/refugerestrooms-ios#116]
See: 
http://nshipster.com/nslocalizedstring/
http://nshipster.com/nslocale/
http://www.raywenderlich.com/64401/internationalization-tutorial-for-ios-2014

**Comment by hkellaway** [comment]
e.g. Info view, 'Directions' and 'Comments' headers, onboarding text

**Comment by DeeDeeG** [comment]
Hi, 

There is a translation set up for the web app, and a Spanish translation is likely to go live on the web app soon. There is some growing interest in tranlating the mobile apps as well.

Is this something you would be interested in getting help with? I'm new to iOS development, and I don't have a Mac (although I may be able to borrow one). But I'd be interested in drawing attention to this task, and contributing myself if I can figure out how to do so.

**Comment by hkellaway** [comment]
i do not currently have the time myself - but happy to support another developer on it. that being said, i've only done english-language apps myself, so i'm no expert.

this tutorial looks pretty handy: https://medium.com/lean-localization/ios-localization-tutorial-938231f9f881

you'll need to be able to run Xcode (version 9 at the moment); im not sure how one can achieve that without a Mac, but i think its possible ?
