### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by K80theSHADE** [RefugeRestrooms/refugerestrooms-ios#145]
Hello! I suggest we have the db in the server use the google api to find and add all state and federal government buildings, offices and outhouses, adding these to a "pending" db, where those of us with experience in these places can choose locations needing descriptions and make one.
Just a thought, seeing's how the 70 square miles around Oklahoma City has nine places on it.
There are a lot more places than that, but nobody on the daily struggle has time to use the app to pin a place on a map.
And quite frankly, it is not our job to find these places.
It is not any woman's job to wear barbed condoms, roofie-detecting nail polish, be armed in public or any of the other stuff it has been suggested we do to "help ourselves" to avoid being raped by men.
Just an example. It is no trans-woman's job to hunt down bathrooms and add them to a database.
You guys ought to be getting PAID by Uncle Sam to be a task force responsible for generating and maintaining a list of places for us based upon a lawyer's reading of the law as it stands today.
It is an outrage that the concept of this app even has to exist, let-alone that it actually does exist.
It needs to exist, beyond question.
But it's one of those objects born of oppression which should be gladly searching for the end of its useful life.

**Comment by nataliegroman** [comment]
K.

**Comment by hkellaway** [comment]
@K80theSHADE thanks for the suggestion and sentiment - this is the repo for the iOS app though; what you've brought up is more appropriate for the web app repo (https://github.com/RefugeRestrooms/refugerestrooms)
