### ISSUE TITLE
Need to be able to test new restroom submission

### ISSUE THREAD

**Issue by DeeDeeG** [RefugeRestrooms/refugerestrooms-ios#154]
In order to test the app properly, it would be great to be able to test submitting a new restroom entry.

However:

- I don't find real gender-neutral bathrooms near where I live every day...
- I don't want to spam with entries that are fake and leave them in the production DB

Can we hook up a testing db to the app somehow?

Or can we communicate where our fake restroom entries will go on the map (Antarctica?), and coordinate to delete them quickly?

Any thoughts on this are appreciated.

**Comment by hkellaway** [comment]
the iOS app simply pushes to the website for Restroom submission. so testing that Restroom submission works on the app is really akin to testing that Restroom submission works on the website. phrased differently, if adding a website is broken on the website then its broken on the app - and there's nothing that could be done in the app's implementation to fix that. and so, i would defer to the web team to test restroom submission

**Comment by DeeDeeG** [comment]
Good point.

**Comment by DeeDeeG** [comment]
There's nothing else I can think of to test. It all works as expected, other than some restrooms not showing up on the map. But that's an existing issue from the previous version, so I wouldn't say that's anything to do with the latest version.

**Comment by hkellaway** [comment]
Thanks for your help testing!
