### ISSUE TITLE
Search quota limited to 1000 requests per day for iOS app

### ISSUE THREAD

**Issue by hkellaway** [RefugeRestrooms/refugerestrooms-ios#155]
Documenting here a change in the request quota to search locations on the iOS app. Google just updated the Google Maps Platform to require Billing information be associated with accounts. We are using the Places API for the iOS app - I associated my own Billing information today. 

However, in order not to be charged, I had to limit the request quota to 1000 requests per day. This seems satisfactory at the moment as requests via the iOS app per day don't currently exceed 1000 - but would have to change in the future if usage increased. However, I would then not want my own banking account to be billed.

Alternatively, if there is another Google Maps Platform account being used for the website that is funded for the project, we might be able to update the iOS app to use that API key. Let me know if that is the case (cc active contributors on web: @mi-wood @DeeDeeG)

**Comment by DeeDeeG** [comment]
I'm not 100% on this, but I believe we are not paying for the Maps API just yet for the website.

We do have an account with billing info associated with it over there, but that's all I know for sure. I'm also not sure how close we are to reaching quota over there.
