### ISSUE TITLE
Fetch latest pins when returning from New Restroom controller

### ISSUE THREAD

**Issue by hkellaway** [RefugeRestrooms/refugerestrooms-ios#97]
Change sync to be based on time instead of just date

**Comment by hkellaway** [comment]
Requires by_date endpoint to be more granular

**Comment by DeeDeeG** [comment]
I know this is an older issue, but I wanted to leave a quick comment.

I think there is an API endpoint that does serve just the latest entries:

Documentation page at production site: https://refugerestrooms.org/api/docs/#!/restrooms/GET_version_restrooms_format

Might be what this issue needs?
